CREATE DATABASE meubanco;
SELECT CURRENT_USER();

CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  senha VARCHAR(255) NOT NULL
);

ALTER TABLE usuarios
ADD COLUMN telefone VARCHAR(20),
ADD COLUMN foto VARCHAR(255);

